# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title
# relative_permalinks: true

# Setup
title:            Dery R A
tagline:          ''
description:      'AI Enthusiast • Software Engineer • Lifelong Learner'
url:              https://deryrahman.github.io
baseurl:          ''
blogurl:          /blog/
paymenturl:       /payment/

author:
  name:           'Dery Rahman A'
  url:            https://deryrahman.github.io

paginate_path:    "/blog/page:num"
paginate:         5

# Custom vars
version:          0.1.2

medium:
    url:          https://medium.com/@deryrahman

github:
  repo:           https://github.com/deryrahman

linkedin:
  url:            https://www.linkedin.com/in/deryrahman
