# Gems
plugins:
  - jekyll-paginate
  - jekyll-gist
  - redcarpet

markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Dery R A
tagline:          ''
description:      'AI Enthusiast • Software Engineer • Long Life Learner'
url:              https://deryrahman.github.io
baseurl:          /
blogurl:          /blog/

author:
  name:           'Dery Rahman A'
  url:            https://deryrahman.github.io

paginate_path: "/blog/page:num/"
paginate:         1

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/deryrahman

linkedin:
  url:            https://www.linkedin.com/in/deryrahman/